### ISSUE TITLE
Looking forward

### ISSUE THREAD

**Issue by LanceVGoss** [bucanero/libun7zip#1]
To this build please could you try and find away to get Sharc files on PlayStation home extracted that would be amazing for loads of us running Home offline. I believe you can do it

https://drive.google.com/drive/folders/1_HNgt9M-EfrlZ54oxYEPbgEuNlPs3Mht
Here is some files loads of us are trying to get into Please help us

**Comment by bucanero** [comment]
Sorry, but I'm not a big fan of reverse-engineering, and to decode these kind of proprietary file formats you really need to RE the binaries to understand what kind of encoding/encryption/compression they're using, before you can even try to extract a file.

Perhaps someone with a good background on RE and the PPU platform can help you out.

**Comment by bucanero** [comment]
The PS Home `sharc` format can be decrypted with this tool:
https://www.psx-place.com/threads/release-playstation-home-sdat-dumper-decrypts-sharc-and-lua.38714/
